#
###################################
# Site wide configuration
####################################
#
title: Jaken Herman
email: JakenHerman7@Gmail.com
description: Software Engineer, Brewer of Beer, Husband
url:
keywords: ["blog", "jaken", "herman", "software", "engineer"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: jaken herman
  avatar: avatar.jpg
  job: "⚾ Front-End Developer for the Houston Astros ⚾"
  bio: "husband | baseball fan | author"
  email: jakenherman7@gmail.com
  disqus-shortname: jakenherman-com
  twitter: 0x6a6368h
  amazon-author: amazon.com/author/jakenherman
  facebook: #username
  google:
    plus: #username
    analytics: UA-134666359-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JakenHerman
  gitlab: #username
  stackoverflow: 2752265/jaken-herman?tab=profile
  linkedin: jakenherman
  skype: jaken2711
  xing: #username
  instagram: jaken.herman
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: jakenherman
  youtube: jakencherman
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: JakenHerman
  reddit: #username
  telegram: #username
  tripadvisor : jakenherman
  strava: jaken_herman
