#
###################################
# Site wide configuration
####################################
#
title: Jaken Herman
email: JakenHerman7@Gmail.com
description: Software Engineer, Brewer of Beer, Husband
url:
keywords: ["blog", "jaken", "herman", "software", "engineer"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: jaken herman
  avatar: avatar.jpg
  job: "ğŸš€ Software Engineer at NASA ğŸ›°ï¸"
  bio: "I'm a full-stack software engineer specializing in the ASP.NET framework in both Visual Basic and C# â€â€ğŸ’». 
        I also work on Mobile Application development using both the Xamarin.Forms framework and Apache Cordova framework depending on the project ğŸ“±.
        I'm well-versed in JavaScript and many of it's popular libraries and frameworks. In my free time, I like to play golf â›³ and brew beer ğŸº.
        I am married to an amazing woman who also works at NASA in Mission Control as a flight controller. We have 2 dogs ğŸ¶, 4 cats ğŸ±, and lots of great
        friends."
  email: jakenherman7@gmail.com
  disqus-shortname: jakenherman-com
  twitter: 0x6a6368h
  facebook: #username
  google:
    plus: #username
    analytics: UA-134666359-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: JakenHerman
  gitlab: #username
  stackoverflow: 2752265/jaken-herman?tab=profile
  linkedin: jakenherman
  skype: jaken2711
  xing: #username
  instagram: jaken.herman
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: jakencherman
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username
  tripadvisor : jakenherman
  #untappd: jakenh